version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
      - "33070:33070"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
